-- place all SQL files, including schema builds under the **sql** folder
-- use the SQL formatter from the Microsoft SQL Server (mssql) VSCode Extension by Microsoft
-- check VSCode option for Format on Save under the File->Preferences->User/Workspace->Text Editor->Formatting
-- remove this placeholder